using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace Odoo.SourceGenerator
{
    [Generator]
    public class OdooModelGenerator : ISourceGenerator
    {
        private int _nextModelToken = 1000;
        private int _nextFieldToken = 1;
        private Dictionary<string, int> _modelTokens = new();
        private Dictionary<(string Model, string Field), int> _fieldTokens = new();

        public void Initialize(GeneratorInitializationContext context)
        {
            // Register a syntax receiver to find interfaces with OdooModel attribute
            context.RegisterForSyntaxNotifications(() => new OdooModelSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not OdooModelSyntaxReceiver receiver)
                return;

            var compilation = context.Compilation;
            var modelData = new List<ModelInfo>();

            // First pass: collect all model and field information
            foreach (var interfaceDecl in receiver.InterfacesToProcess)
            {
                var model = compilation.GetSemanticModel(interfaceDecl.SyntaxTree);
                var interfaceSymbol = model.GetDeclaredSymbol(interfaceDecl);
                
                if (interfaceSymbol == null)
                    continue;

                var modelName = GetOdooModelName(interfaceSymbol);
                if (string.IsNullOrEmpty(modelName))
                    continue;

                var info = new ModelInfo
                {
                    InterfaceSymbol = interfaceSymbol,
                    ModelName = modelName,
                    Properties = GetAllProperties(interfaceSymbol)
                };

                // Assign tokens
                if (!_modelTokens.ContainsKey(modelName))
                {
                    _modelTokens[modelName] = _nextModelToken++;
                }
                info.ModelToken = _modelTokens[modelName];

                // Assign field tokens
                foreach (var prop in info.Properties)
                {
                    var fieldName = GetOdooFieldName(prop);
                    var key = (modelName, fieldName);
                    if (!_fieldTokens.ContainsKey(key))
                    {
                        _fieldTokens[key] = _nextFieldToken++;
                    }
                }

                modelData.Add(info);
            }

            // Generate ModelSchema
            var schemaSource = GenerateModelSchema(modelData);
            context.AddSource("ModelSchema.g.cs", SourceText.From(schemaSource, Encoding.UTF8));

            // Generate for each model
            foreach (var info in modelData)
            {
                // Generate BatchContext
                var batchContextSource = GenerateBatchContext(info);
                var batchContextName = $"{info.InterfaceSymbol.Name.Substring(1)}BatchContext.g.cs";
                context.AddSource(batchContextName, SourceText.From(batchContextSource, Encoding.UTF8));

                // Generate Record struct
                var recordSource = GenerateRecordStruct(info);
                var recordName = $"{info.InterfaceSymbol.Name}Record.g.cs";
                context.AddSource(recordName, SourceText.From(recordSource, Encoding.UTF8));
            }

            // Generate environment extensions
            var extensionsSource = GenerateEnvironmentExtensions(modelData);
            context.AddSource("OdooEnvironmentExtensions.g.cs", SourceText.From(extensionsSource, Encoding.UTF8));
        }

        private string GenerateModelSchema(List<ModelInfo> models)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using Odoo.Core;");
            sb.AppendLine();
            sb.AppendLine("namespace Odoo.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Static schema registry with compile-time field and model tokens.");
            sb.AppendLine("    /// Eliminates string hashing overhead for cache lookups.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class ModelSchema");
            sb.AppendLine("    {");

            foreach (var model in models)
            {
                var className = model.InterfaceSymbol.Name.Substring(1); // Remove 'I'
                
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Schema for {model.ModelName}");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public static class {className}");
                sb.AppendLine("        {");
                sb.AppendLine($"            public static readonly ModelHandle ModelToken = new({model.ModelToken});");
                sb.AppendLine($"            public const string ModelName = \"{model.ModelName}\";");
                sb.AppendLine();

                // Add field tokens
                foreach (var prop in model.Properties)
                {
                    var fieldName = GetOdooFieldName(prop);
                    var key = (model.ModelName, fieldName);
                    var token = _fieldTokens[key];
                    
                    sb.AppendLine($"            /// <summary>Field: {fieldName}</summary>");
                    sb.AppendLine($"            public static readonly FieldHandle {prop.Name} = new({token});");
                }

                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private string GenerateBatchContext(ModelInfo model)
        {
            var sb = new StringBuilder();
            var namespaceName = model.InterfaceSymbol.ContainingNamespace.ToDisplayString();
            var className = model.InterfaceSymbol.Name.Substring(1); // Remove 'I'
            var contextName = $"{className}BatchContext";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Odoo.Core;");
            sb.AppendLine("using Odoo.Generated;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Batch context for efficient {className} record iteration.");
            sb.AppendLine($"    /// Lives on the stack, caches column spans for batch access.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public ref struct {contextName}");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IColumnarCache _cache;");
            sb.AppendLine("        private readonly int[] _ids;");
            sb.AppendLine();

            // Generate column span fields
            foreach (var prop in model.Properties)
            {
                var propertyType = prop.Type.ToDisplayString();
                sb.AppendLine($"        private ReadOnlySpan<{propertyType}> _{ToCamelCase(prop.Name)}Column;");
                sb.AppendLine($"        private bool _{ToCamelCase(prop.Name)}Loaded;");
            }

            sb.AppendLine();
            sb.AppendLine($"        public {contextName}(IColumnarCache cache, int[] ids)");
            sb.AppendLine("        {");
            sb.AppendLine("            _cache = cache;");
            sb.AppendLine("            _ids = ids;");
            
            // Initialize all fields to default
            foreach (var prop in model.Properties)
            {
                sb.AppendLine($"            _{ToCamelCase(prop.Name)}Column = default;");
                sb.AppendLine($"            _{ToCamelCase(prop.Name)}Loaded = false;");
            }
            
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate lazy loader methods for each column
            foreach (var prop in model.Properties)
            {
                var propertyType = prop.Type.ToDisplayString();
                var camelName = ToCamelCase(prop.Name);
                
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Get the {prop.Name} column (lazy-loaded)");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public ReadOnlySpan<{propertyType}> Get{prop.Name}Column()");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (!_{camelName}Loaded)");
                sb.AppendLine("            {");
                sb.AppendLine($"                _{camelName}Column = _cache.GetColumnSpan<{propertyType}>(");
                sb.AppendLine($"                    ModelSchema.{className}.ModelToken,");
                sb.AppendLine($"                    _ids,");
                sb.AppendLine($"                    ModelSchema.{className}.{prop.Name}");
                sb.AppendLine("                );");
                sb.AppendLine($"                _{camelName}Loaded = true;");
                sb.AppendLine("            }");
                sb.AppendLine($"            return _{camelName}Column;");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private string GenerateRecordStruct(ModelInfo model)
        {
            var sb = new StringBuilder();
            var namespaceName = model.InterfaceSymbol.ContainingNamespace.ToDisplayString();
            var recordName = model.InterfaceSymbol.Name.Substring(1) + "Record";
            var className = model.InterfaceSymbol.Name.Substring(1);
            var batchContextName = $"{className}BatchContext";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Odoo.Core;");
            sb.AppendLine("using Odoo.Generated;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Generated record struct for {model.InterfaceSymbol.Name}");
            sb.AppendLine($"    /// Model: {model.ModelName}");
            sb.AppendLine($"    /// Supports both single-record and batch access patterns.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public readonly struct {recordName} : {model.InterfaceSymbol.ToDisplayString()}");
            sb.AppendLine("    {");
            
            // Fields
            sb.AppendLine("        private readonly IEnvironment _env;");
            sb.AppendLine("        private readonly int _id;");
            sb.AppendLine();

            // Constructor
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Create a record instance");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public {recordName}(IEnvironment env, int id)");
            sb.AppendLine("        {");
            sb.AppendLine("            _env = env;");
            sb.AppendLine("            _id = id;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // IOdooRecord properties
            sb.AppendLine("        public int Id => _id;");
            sb.AppendLine("        public IEnvironment Env => _env;");
            sb.AppendLine();

            // Generate properties with dual access mode
            foreach (var prop in model.Properties)
            {
                GenerateOptimizedProperty(sb, prop, model, className);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private void GenerateOptimizedProperty(StringBuilder sb, IPropertySymbol property, ModelInfo model, string className)
        {
            var propertyType = property.Type.ToDisplayString();
            
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Odoo field: {GetOdooFieldName(property)}");
            sb.AppendLine($"        /// </summary>");

            if (property.IsReadOnly)
            {
                // Read-only property using columnar cache
                sb.AppendLine($"        public {propertyType} {property.Name}");
                sb.AppendLine("        {");
                sb.AppendLine("            [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"            get => _env.Columns.GetValue<{propertyType}>(");
                sb.AppendLine($"                ModelSchema.{className}.ModelToken,");
                sb.AppendLine($"                _id,");
                sb.AppendLine($"                ModelSchema.{className}.{property.Name});");
                sb.AppendLine("        }");
            }
            else
            {
                // Read-write property
                sb.AppendLine($"        public {propertyType} {property.Name}");
                sb.AppendLine("        {");
                sb.AppendLine("            [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"            get => _env.Columns.GetValue<{propertyType}>(");
                sb.AppendLine($"                ModelSchema.{className}.ModelToken,");
                sb.AppendLine($"                _id,");
                sb.AppendLine($"                ModelSchema.{className}.{property.Name});");
                sb.AppendLine("            set");
                sb.AppendLine("            {");
                sb.AppendLine($"                _env.Columns.SetValue(");
                sb.AppendLine($"                    ModelSchema.{className}.ModelToken,");
                sb.AppendLine($"                    _id,");
                sb.AppendLine($"                    ModelSchema.{className}.{property.Name},");
                sb.AppendLine($"                    value);");
                sb.AppendLine($"                _env.Columns.MarkDirty(");
                sb.AppendLine($"                    ModelSchema.{className}.ModelToken,");
                sb.AppendLine($"                    _id,");
                sb.AppendLine($"                    ModelSchema.{className}.{property.Name});");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
            sb.AppendLine();
        }

        private string GenerateEnvironmentExtensions(List<ModelInfo> models)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using Odoo.Core;");
            sb.AppendLine("using Odoo.Models;");
            sb.AppendLine("using Odoo.Models.Generated;");
            sb.AppendLine();
            sb.AppendLine("namespace Odoo.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated extension methods for IEnvironment");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class OdooEnvironmentExtensions");
            sb.AppendLine("    {");

            foreach (var model in models)
            {
                var recordName = model.InterfaceSymbol.Name.Substring(1) + "Record";
                var methodName = model.InterfaceSymbol.Name.Substring(1) + "s";
                var singleMethodName = model.InterfaceSymbol.Name.Substring(1);

                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Get a recordset for {model.InterfaceSymbol.Name}");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public static RecordSet<{model.InterfaceSymbol.ToDisplayString()}> {methodName}(");
                sb.AppendLine($"            this IEnvironment env,");
                sb.AppendLine($"            int[] ids)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return new RecordSet<{model.InterfaceSymbol.ToDisplayString()}>(");
                sb.AppendLine($"                env,");
                sb.AppendLine($"                \"{model.ModelName}\",");
                sb.AppendLine($"                ids,");
                sb.AppendLine($"                (e, id) => new {recordName}(e, id));");
                sb.AppendLine("        }");
                sb.AppendLine();

                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Get a single record for {model.InterfaceSymbol.Name}");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public static {model.InterfaceSymbol.ToDisplayString()} {singleMethodName}(");
                sb.AppendLine($"            this IEnvironment env,");
                sb.AppendLine($"            int id)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return new {recordName}(env, id);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private List<IPropertySymbol> GetAllProperties(INamedTypeSymbol interfaceSymbol)
        {
            var properties = new List<IPropertySymbol>();
            var visited = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

            void CollectProperties(INamedTypeSymbol symbol)
            {
                if (!visited.Add(symbol))
                    return;

                foreach (var member in symbol.GetMembers())
                {
                    if (member is IPropertySymbol property && 
                        property.Name != "Id" && 
                        property.Name != "Env")
                    {
                        properties.Add(property);
                    }
                }

                foreach (var baseInterface in symbol.Interfaces)
                {
                    CollectProperties(baseInterface);
                }
            }

            CollectProperties(interfaceSymbol);
            return properties;
        }

        private string GetOdooModelName(INamedTypeSymbol interfaceSymbol)
        {
            var attribute = interfaceSymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "OdooModelAttribute");

            if (attribute?.ConstructorArguments.Length > 0)
            {
                return attribute.ConstructorArguments[0].Value?.ToString() ?? "";
            }

            return "";
        }

        private string GetOdooFieldName(IPropertySymbol property)
        {
            var attribute = property.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "OdooFieldAttribute");

            if (attribute?.ConstructorArguments.Length > 0)
            {
                return attribute.ConstructorArguments[0].Value?.ToString() ?? property.Name.ToLower();
            }

            return property.Name.ToLower();
        }

        private string ToCamelCase(string value)
        {
            if (string.IsNullOrEmpty(value) || char.IsLower(value[0]))
                return value;
            
            return char.ToLower(value[0]) + value.Substring(1);
        }

        private class ModelInfo
        {
            public INamedTypeSymbol InterfaceSymbol { get; set; } = null!;
            public string ModelName { get; set; } = "";
            public int ModelToken { get; set; }
            public List<IPropertySymbol> Properties { get; set; } = new();
        }
    }

    internal class OdooModelSyntaxReceiver : ISyntaxReceiver
    {
        public List<InterfaceDeclarationSyntax> InterfacesToProcess { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is InterfaceDeclarationSyntax interfaceDecl &&
                interfaceDecl.AttributeLists.Count > 0)
            {
                InterfacesToProcess.Add(interfaceDecl);
            }
        }
    }
}