using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace Odoo.SourceGenerator
{
    [Generator]
    public class OdooModelGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // Register a syntax receiver to find interfaces with OdooModel attribute
            context.RegisterForSyntaxNotifications(() => new OdooModelSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not OdooModelSyntaxReceiver receiver)
                return;

            var compilation = context.Compilation;

            // Process each interface marked with OdooModel
            foreach (var interfaceDecl in receiver.InterfacesToProcess)
            {
                var model = compilation.GetSemanticModel(interfaceDecl.SyntaxTree);
                var interfaceSymbol = model.GetDeclaredSymbol(interfaceDecl);
                
                if (interfaceSymbol == null)
                    continue;

                // Generate the record struct
                var source = GenerateRecordStruct(interfaceSymbol, compilation);
                var fileName = $"{interfaceSymbol.Name}Record.g.cs";
                
                context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
            }

            // Generate the environment extensions
            var extensionsSource = GenerateEnvironmentExtensions(receiver.InterfacesToProcess, compilation);
            context.AddSource("OdooEnvironmentExtensions.g.cs", SourceText.From(extensionsSource, Encoding.UTF8));
        }

        private string GenerateRecordStruct(INamedTypeSymbol interfaceSymbol, Compilation compilation)
        {
            var sb = new StringBuilder();
            var namespaceName = interfaceSymbol.ContainingNamespace.ToDisplayString();
            var recordName = interfaceSymbol.Name.Substring(1) + "Record"; // Remove 'I' prefix
            var modelName = GetOdooModelName(interfaceSymbol);

            // Collect all properties from the interface hierarchy
            var allProperties = GetAllProperties(interfaceSymbol);

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using Odoo.Core;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Generated record struct for {interfaceSymbol.Name}");
            sb.AppendLine($"    /// Model: {modelName}");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public readonly struct {recordName} : {interfaceSymbol.ToDisplayString()}");
            sb.AppendLine("    {");
            
            // Fields
            sb.AppendLine("        private readonly IEnvironment _env;");
            sb.AppendLine("        private readonly int _id;");
            sb.AppendLine($"        private const string ModelName = \"{modelName}\";");
            sb.AppendLine();

            // Constructor
            sb.AppendLine($"        public {recordName}(IEnvironment env, int id)");
            sb.AppendLine("        {");
            sb.AppendLine("            _env = env;");
            sb.AppendLine("            _id = id;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // IOdooRecord properties
            sb.AppendLine("        public int Id => _id;");
            sb.AppendLine("        public IEnvironment Env => _env;");
            sb.AppendLine();

            // Generate properties
            foreach (var prop in allProperties)
            {
                GenerateProperty(sb, prop, interfaceSymbol);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private void GenerateProperty(StringBuilder sb, IPropertySymbol property, INamedTypeSymbol modelInterface)
        {
            var fieldName = GetOdooFieldName(property);
            var propertyType = property.Type.ToDisplayString();
            var modelName = GetOdooModelName(modelInterface);

            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Odoo field: {fieldName}");
            sb.AppendLine($"        /// </summary>");

            if (property.IsReadOnly)
            {
                // Read-only property
                sb.AppendLine($"        public {propertyType} {property.Name}");
                sb.AppendLine("        {");
                sb.AppendLine($"            get => _env.Cache.GetValue<{propertyType}>(ModelName, _id, \"{fieldName}\");");
                sb.AppendLine("        }");
            }
            else
            {
                // Read-write property
                sb.AppendLine($"        public {propertyType} {property.Name}");
                sb.AppendLine("        {");
                sb.AppendLine($"            get => _env.Cache.GetValue<{propertyType}>(ModelName, _id, \"{fieldName}\");");
                sb.AppendLine($"            set");
                sb.AppendLine("            {");
                sb.AppendLine($"                _env.Cache.SetValue(ModelName, _id, \"{fieldName}\", value);");
                sb.AppendLine($"                _env.Cache.MarkDirty(ModelName, _id, \"{fieldName}\");");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
            sb.AppendLine();
        }

        private string GenerateEnvironmentExtensions(List<InterfaceDeclarationSyntax> interfaces, Compilation compilation)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using Odoo.Core;");
            sb.AppendLine("using Odoo.Models;");
            sb.AppendLine("using Odoo.Models.Generated;");
            sb.AppendLine();
            sb.AppendLine("namespace Odoo.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated extension methods for IEnvironment");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class OdooEnvironmentExtensions");
            sb.AppendLine("    {");

            foreach (var interfaceDecl in interfaces)
            {
                var model = compilation.GetSemanticModel(interfaceDecl.SyntaxTree);
                var interfaceSymbol = model.GetDeclaredSymbol(interfaceDecl);
                
                if (interfaceSymbol == null)
                    continue;

                var recordName = interfaceSymbol.Name.Substring(1) + "Record";
                var modelName = GetOdooModelName(interfaceSymbol);
                var methodName = interfaceSymbol.Name.Substring(1) + "s"; // Pluralize

                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Get a recordset for {interfaceSymbol.Name}");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public static RecordSet<{interfaceSymbol.ToDisplayString()}> {methodName}(");
                sb.AppendLine($"            this IEnvironment env,");
                sb.AppendLine($"            int[] ids)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return new RecordSet<{interfaceSymbol.ToDisplayString()}>(");
                sb.AppendLine($"                env,");
                sb.AppendLine($"                \"{modelName}\",");
                sb.AppendLine($"                ids,");
                sb.AppendLine($"                (e, id) => new {recordName}(e, id));");
                sb.AppendLine("        }");
                sb.AppendLine();

                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Get a single record for {interfaceSymbol.Name}");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public static {interfaceSymbol.ToDisplayString()} {interfaceSymbol.Name.Substring(1)}(");
                sb.AppendLine($"            this IEnvironment env,");
                sb.AppendLine($"            int id)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return new {recordName}(env, id);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private List<IPropertySymbol> GetAllProperties(INamedTypeSymbol interfaceSymbol)
        {
            var properties = new List<IPropertySymbol>();
            var visited = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

            void CollectProperties(INamedTypeSymbol symbol)
            {
                if (!visited.Add(symbol))
                    return;

                // Add properties from this interface
                foreach (var member in symbol.GetMembers())
                {
                    if (member is IPropertySymbol property && 
                        property.Name != "Id" && 
                        property.Name != "Env")
                    {
                        properties.Add(property);
                    }
                }

                // Recursively collect from base interfaces
                foreach (var baseInterface in symbol.Interfaces)
                {
                    CollectProperties(baseInterface);
                }
            }

            CollectProperties(interfaceSymbol);
            return properties;
        }

        private string GetOdooModelName(INamedTypeSymbol interfaceSymbol)
        {
            var attribute = interfaceSymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "OdooModelAttribute");

            if (attribute?.ConstructorArguments.Length > 0)
            {
                return attribute.ConstructorArguments[0].Value?.ToString() ?? "";
            }

            return "";
        }

        private string GetOdooFieldName(IPropertySymbol property)
        {
            var attribute = property.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "OdooFieldAttribute");

            if (attribute?.ConstructorArguments.Length > 0)
            {
                return attribute.ConstructorArguments[0].Value?.ToString() ?? property.Name.ToLower();
            }

            return property.Name.ToLower();
        }
    }

    internal class OdooModelSyntaxReceiver : ISyntaxReceiver
    {
        public List<InterfaceDeclarationSyntax> InterfacesToProcess { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            // Look for interfaces with attributes
            if (syntaxNode is InterfaceDeclarationSyntax interfaceDecl &&
                interfaceDecl.AttributeLists.Count > 0)
            {
                InterfacesToProcess.Add(interfaceDecl);
            }
        }
    }
}