using Xunit;
using Odoo.Core;
using Odoo.Core.Modules;
using Odoo.Core.Pipeline;
using Odoo.Base.Models;
using Odoo.Sale.Models;
// Import generated code - these are auto-generated by the source generator
// Alias to avoid ambiguity with Odoo.Core.Modules.ModelSchema
using OdooTests = Odoo.Generated.OdooTests;
using OdooBase = Odoo.Generated.OdooBase;
using Odoo.Generated.OdooTests;

namespace Odoo.Tests;

/// <summary>
/// Tests demonstrating typical Odoo developer usage patterns.
/// 
/// This shows what a developer using the "sale" addon would experience:
/// - Creating partners with simple C# property syntax
/// - Computed fields (DisplayName) auto-calculating on dependency changes
/// - Sale module extending base partner with IsCustomer/CreditLimit
/// - Pipeline customizations automatically applied
/// 
/// Under the hood, the source generator creates:
/// - ResPartner class (unified wrapper implementing all interfaces)
/// - ResPartnerPipelines (Write/Create pipelines, computed field triggers)
/// - ModelSchema (compile-time field tokens)
/// - ModuleRegistrar (auto-registers everything)
/// </summary>
public class PartnerUsageTests
{
    #region Test Setup

    /// <summary>
    /// Creates a fully configured OdooEnvironment with all pipelines registered.
    /// This mimics what happens at app startup when modules are loaded.
    /// </summary>
    private static OdooEnvironment CreateConfiguredEnvironment()
    {
        // 1. Create registries
        var pipelineRegistry = new PipelineRegistry();
        var registryBuilder = new RegistryBuilder();
        
        // 2. Scan for models from referenced assemblies
        registryBuilder.ScanAssembly(typeof(IPartnerBase).Assembly);     // Odoo.Base
        registryBuilder.ScanAssembly(typeof(IPartnerSaleExtension).Assembly); // Odoo.Sale
        var modelRegistry = registryBuilder.Build();
        
        // 3. Register pipelines and factories from generated code
        // Like Odoo's module loading - each module registers its own pipelines
        
        // First, register pipelines from Odoo.Base (contains PartnerLogic.ComputeDisplayName)
        var baseRegistrar = new OdooBase.ModuleRegistrar();
        baseRegistrar.RegisterPipelines(pipelineRegistry);
        
        // Then register from this test assembly's generated code
        // This contains the unified ResPartner wrapper that sees all interfaces
        var testRegistrar = new ModuleRegistrar();
        testRegistrar.RegisterPipelines(pipelineRegistry);
        testRegistrar.RegisterFactories(modelRegistry);
        
        // 4. Compile pipelines (builds delegate chains)
        pipelineRegistry.CompileAll();
        
        // 5. Create environment
        return new OdooEnvironment(userId: 1, null, modelRegistry, pipelineRegistry);
    }

    #endregion

    #region Basic Partner Creation

    [Fact]
    public void CreatePartner_WithName_SetsDisplayName()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        
        // Act - Simple partner creation with property initializer style
        var partner = ResPartnerPipelines.Create(env, new() 
        { 
            { "name", "Alice" } 
        });
        
        // Assert - DisplayName is automatically computed
        Assert.Equal("Alice", partner.Name);
        Assert.Equal("Alice", partner.DisplayName); // Computed!
    }

    [Fact]
    public void CreatePartner_AsCompany_DisplayNameShowsCompanySuffix()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        
        // Act - Create a company partner
        var company = ResPartnerPipelines.Create(env, new()
        {
            { "name", "Acme Corp" },
            { "is_company", true }
        });
        
        // Assert - DisplayName shows "Name | Company" format
        Assert.True(company.IsCompany);
        Assert.Equal("Acme Corp | Company", company.DisplayName);
    }

    #endregion

    #region Computed Fields Auto-Update

    [Fact]
    public void ChangePartnerName_DisplayNameAutoUpdates()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var partner = ResPartnerPipelines.Create(env, new() { { "name", "Bob" } });
        Assert.Equal("Bob", partner.DisplayName);
        
        // Act - Change name using simple property setter
        partner.Name = "Robert";
        
        // Assert - DisplayName auto-updated via compute method
        Assert.Equal("Robert", partner.DisplayName);
    }

    [Fact]
    public void ChangeIsCompany_DisplayNameFormatChanges()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var partner = ResPartnerPipelines.Create(env, new() { { "name", "Alice" } });
        Assert.Equal("Alice", partner.DisplayName); // Individual format
        
        // Act - Change to company
        partner.IsCompany = true;
        
        // Assert - DisplayName format changed to company format
        Assert.Equal("Alice | Company", partner.DisplayName);
    }

    #endregion

    #region Sale Module Extensions

    [Fact]
    public void SaleModuleFields_AvailableOnPartner()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        
        // Act - Create partner with sale module fields
        var customer = ResPartnerPipelines.Create(env, new()
        {
            { "name", "Premium Customer" },
            { "is_customer", true },
            { "credit_limit", 5000.00m }
        });
        
        // Assert - Sale fields accessible via IPartnerSaleExtension
        Assert.True(customer.IsCustomer);
        Assert.Equal(5000.00m, customer.CreditLimit);
        
        // Can also access base fields
        Assert.Equal("Premium Customer", customer.Name);
    }

    [Fact]
    public void UnifiedWrapper_SameInstanceForDifferentInterfaces()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var partner = ResPartnerPipelines.Create(env, new() { { "name", "Test" } });
        
        // Act - Get same record via different interface
        var asBase = env.GetRecord<IPartnerBase>("res.partner", partner.Id);
        var asSale = env.GetRecord<IPartnerSaleExtension>("res.partner", partner.Id);
        
        // Assert - Identity map returns SAME instance
        Assert.Same(asBase, asSale);
        Assert.Same(partner, asBase);
    }

    #endregion

    #region Property Setters Trigger Write Pipeline

    [Fact]
    public void PropertySetter_GoesThruWritePipeline()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var partner = ResPartnerPipelines.Create(env, new() { { "name", "Test" } });
        
        // Act - Property setter triggers Write pipeline
        // Under the hood: partner.Email = x → ResPartnerPipelines.Write(handle, { "email": x })
        partner.Email = "test@example.com";
        
        // Assert - Value is stored
        Assert.Equal("test@example.com", partner.Email);
        
        // The DirtyTracker would have the field marked as dirty
        Assert.True(env.DirtyTracker.IsFieldDirty(
            OdooTests.ModelSchema.ResPartner.ModelToken,
            partner.Id,
            OdooTests.ModelSchema.ResPartner.Email));
    }

    #endregion

    #region RecordSet Operations

    [Fact]
    public void RecordSet_FilterAndIterate()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var p1 = ResPartnerPipelines.Create(env, new() { { "name", "Individual 1" }, { "is_company", false } });
        var p2 = ResPartnerPipelines.Create(env, new() { { "name", "Company A" }, { "is_company", true } });
        var p3 = ResPartnerPipelines.Create(env, new() { { "name", "Company B" }, { "is_company", true } });
        
        // Act - Get records and filter
        var allPartners = env.GetRecords<IPartnerBase>("res.partner", new[] { p1.Id, p2.Id, p3.Id });
        var companies = allPartners.Where(p => p.IsCompany);
        
        // Assert
        Assert.Equal(3, allPartners.Count);
        Assert.Equal(2, companies.Count);
        Assert.All(companies, c => Assert.True(c.IsCompany));
    }

    #endregion

    #region Computed Field Protection Mechanism

    [Fact]
    public void ComputedField_CannotBeSetDirectlyOutsideCompute()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var partner = ResPartnerPipelines.Create(env, new() { { "name", "Test" } });
        
        // Act & Assert - Trying to set computed field outside compute throws
        var ex = Assert.Throws<InvalidOperationException>(() =>
        {
            partner.DisplayName = "Arbitrary Value";
        });
        
        Assert.Contains("computed field", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    #endregion
}