using Odoo.Base.Models;
using Odoo.Core;
using Odoo.Core.Modules;
using Odoo.Core.Pipeline;
using Odoo.Generated.OdooTests;
using Odoo.Sale.Models;
using Xunit;
using OdooBase = Odoo.Generated.OdooBase;
// Import generated code - these are auto-generated by the source generator
// Alias to avoid ambiguity with Odoo.Core.Modules.ModelSchema
using OdooTests = Odoo.Generated.OdooTests;

namespace Odoo.Tests;

/// <summary>
/// Tests demonstrating typical Odoo developer usage patterns.
///
/// This shows what a developer using the "sale" addon would experience:
/// - Creating partners with simple C# property syntax
/// - Computed fields (DisplayName) auto-calculating on dependency changes
/// - Sale module extending base partner with IsCustomer/CreditLimit
/// - Pipeline customizations automatically applied
///
/// Under the hood, the source generator creates:
/// - ResPartner class (unified wrapper implementing all interfaces)
/// - ResPartnerPipelines (Write/Create pipelines, computed field triggers)
/// - ModelSchema (compile-time field tokens)
/// - ModuleRegistrar (auto-registers everything)
/// </summary>
public class PartnerUsageTests
{
    #region Test Setup

    /// <summary>
    /// Creates a fully configured OdooEnvironment with all pipelines registered.
    /// This mimics what happens at app startup when modules are loaded.
    /// </summary>
    private static OdooEnvironment CreateConfiguredEnvironment()
    {
        return new OdooEnvironmentBuilder().WithUserId(1).Build();
    }

    #endregion

    #region Basic Partner Creation

    [Fact]
    public void CreatePartner_WithName_SetsDisplayName()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();

        // Act - Simple partner creation with typed initializer style

        var partner = env.Create(new() { Name = "Alice" });

        // Assert - DisplayName is automatically computed
        Assert.Equal("Alice", partner.Name);
        Assert.Equal("Alice", partner.DisplayName); // Computed!
    }

    [Fact]
    public void CreatePartner_AsCompany_DisplayNameShowsCompanySuffix()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();

        // Act - Create a company partner
        var company = ResPartnerPipelines.Create(
            env,
            new() { Name = "Acme Corp", IsCompany = true }
        );

        // Assert - DisplayName shows "Name | Company" format
        Assert.True(company.IsCompany);
        Assert.Equal("Acme Corp | Company", company.DisplayName);
        company.Name = "Oteny";
        Assert.Equal("Oteny | Company", company.DisplayName);
    }

    #endregion

    #region Computed Fields Auto-Update

    [Fact]
    public void ChangePartnerName_DisplayNameAutoUpdates()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var partner = ResPartnerPipelines.CreateFromDict(env, new() { { "name", "Bob" } });
        Assert.Equal("Bob", partner.DisplayName);

        // Act - Change name using simple property setter
        partner.Name = "Robert";

        // Assert - DisplayName auto-updated via compute method
        Assert.Equal("Robert", partner.DisplayName);
    }

    #endregion

    #region Sale Module Extensions

    [Fact]
    public void SaleModuleFields_AvailableOnPartner()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();

        // Act - Create partner with sale module fields
        var customer = ResPartnerPipelines.CreateFromDict(
            env,
            new()
            {
                { "name", "Premium Customer" },
                { "is_customer", true },
                { "credit_limit", 5000.00m },
            }
        );

        // Assert - Sale fields accessible via IPartnerSaleExtension
        Assert.True(customer.IsCustomer);
        Assert.Equal(5000.00m, customer.CreditLimit);

        // Can also access base fields
        Assert.Equal("Premium Customer", customer.Name);
    }

    [Fact]
    public void UnifiedWrapper_SameInstanceForDifferentInterfaces()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var partner = ResPartnerPipelines.CreateFromDict(env, new() { { "name", "Test" } });

        // Act - Get same record via different interface
        var asBase = env.GetRecord<IPartnerBase>("res.partner", partner.Id);
        var asSale = env.GetRecord<IPartnerSaleExtension>("res.partner", partner.Id);

        // Assert - Identity map returns SAME instance
        Assert.Same(asBase, asSale);
        Assert.Same(partner, asBase);
    }

    #endregion

    #region Property Setters Trigger Write Pipeline

    [Fact]
    public void PropertySetter_GoesThruWritePipeline()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var partner = ResPartnerPipelines.CreateFromDict(env, new() { { "name", "Test" } });

        // Act - Property setter triggers Write pipeline
        // Under the hood: partner.Email = x → ResPartnerPipelines.Write(handle, { "email": x })
        partner.Email = "test@example.com";

        // Assert - Value is stored
        Assert.Equal("test@example.com", partner.Email);

        // The DirtyTracker would have the field marked as dirty
        Assert.True(
            env.DirtyTracker.IsFieldDirty(
                OdooTests.ModelSchema.ResPartner.ModelToken,
                partner.Id,
                OdooTests.ModelSchema.ResPartner.Email
            )
        );
    }

    #endregion

    #region RecordSet Operations

    [Fact]
    public void RecordSet_FilterAndIterate()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var p1 = ResPartnerPipelines.CreateFromDict(
            env,
            new() { { "name", "Individual 1" }, { "is_company", false } }
        );
        var p2 = ResPartnerPipelines.CreateFromDict(
            env,
            new() { { "name", "Company A" }, { "is_company", true } }
        );
        var p3 = ResPartnerPipelines.CreateFromDict(
            env,
            new() { { "name", "Company B" }, { "is_company", true } }
        );

        // Act - Get records and filter
        var allPartners = env.GetRecords<IPartnerBase>(
            "res.partner",
            new[] { p1.Id, p2.Id, p3.Id }
        );
        var companies = allPartners.Where(p => p.IsCompany);

        // Assert
        Assert.Equal(3, allPartners.Count);
        Assert.Equal(2, companies.Count);
        Assert.All(companies, c => Assert.True(c.IsCompany));
    }

    #endregion

    #region Computed Field Protection Mechanism

    [Fact]
    public void ComputedField_CannotBeSetDirectlyOutsideCompute()
    {
        // Arrange
        var env = CreateConfiguredEnvironment();
        var partner = ResPartnerPipelines.CreateFromDict(env, new() { { "name", "Test" } });

        // Act & Assert - Trying to set computed field outside compute throws
        var ex = Assert.Throws<InvalidOperationException>(() =>
        {
            partner.DisplayName = "Arbitrary Value";
        });

        Assert.Contains("computed field", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    #endregion
}
